# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed8cc454e5a7ccb73fb40bbbe47d822dc4dd12774648a5a0375f3512bbd3f3b6e67f6318d391aec7b9d017503f42186517ec695aa9ad9a6589db9b86be1e4b1a

test:
  secret_key_base: c37c41bb60527853745d4d5661fd5aee60cd6b6ff7621a43be25b2ef5f11128d298f2952f323992ee605f0beaae1c147dfa42c42b3c3cbdb8e8de0c60d5b80b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
